spring:
  datasource:
    username: sa
    url: jdbc:h2:~/motorcycle;DB_CLOSE_ON_EXIT=FALSE
    name: motorcycle
  h2:
    console:
      enabled: true
      path: /db
  jpa:
    hibernate:
      ddl-auto: create-drop
